libraries/ghc-boot-th_dist-install_VERSION = 8.8.2
libraries/ghc-boot-th_dist-install_COMPONENT_ID = ghc-boot-th-8.8.2
libraries/ghc-boot-th_dist-install_MODULES = GHC.LanguageExtensions.Type GHC.ForeignSrcLang.Type GHC.Lexeme
libraries/ghc-boot-th_dist-install_HIDDEN_MODULES = 
libraries/ghc-boot-th_dist-install_SYNOPSIS =Shared functionality between GHC and the @template-haskell@ library
libraries/ghc-boot-th_dist-install_HS_SRC_DIRS = .
libraries/ghc-boot-th_dist-install_DEPS = base-4.13.0.0
libraries/ghc-boot-th_dist-install_DEP_IPIDS = base-4.13.0.0
libraries/ghc-boot-th_dist-install_DEP_NAMES = base
libraries/ghc-boot-th_dist-install_DEP_COMPONENT_IDS = base-4.13.0.0
libraries/ghc-boot-th_dist-install_TRANSITIVE_DEP_NAMES = base integer-gmp ghc-prim rts
libraries/ghc-boot-th_dist-install_TRANSITIVE_DEP_COMPONENT_IDS = base-4.13.0.0 integer-gmp-1.0.2.0 ghc-prim-0.5.3 rts
libraries/ghc-boot-th_dist-install_INCLUDE_DIRS = 
libraries/ghc-boot-th_dist-install_INCLUDES = 
libraries/ghc-boot-th_dist-install_INSTALL_INCLUDES = 
libraries/ghc-boot-th_dist-install_EXTRA_LIBRARIES = 
libraries/ghc-boot-th_dist-install_EXTRA_LIBDIRS = 
libraries/ghc-boot-th_dist-install_S_SRCS = 
libraries/ghc-boot-th_dist-install_C_SRCS  = 
libraries/ghc-boot-th_dist-install_CMM_SRCS = 
libraries/ghc-boot-th_dist-install_DATA_FILES = 
libraries/ghc-boot-th_dist-install_HC_OPTS = -XHaskell2010 -XNoImplicitPrelude
libraries/ghc-boot-th_dist-install_CC_OPTS = 
libraries/ghc-boot-th_dist-install_CPP_OPTS = 
libraries/ghc-boot-th_dist-install_LD_OPTS = 
libraries/ghc-boot-th_dist-install_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/home/abhir00p/ghc-8.8.2/libraries/base/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build/dist-install/build/dist-install/build/include' '/home/abhir00p/ghc-8.8.2/rts/dist/build' '/home/abhir00p/ghc-8.8.2/includes' '/home/abhir00p/ghc-8.8.2/includes/dist-derivedconstants/header'
libraries/ghc-boot-th_dist-install_DEP_CC_OPTS = 
libraries/ghc-boot-th_dist-install_DEP_LIB_DIRS_SEARCHPATH = /home/abhir00p/ghc-8.8.2/libraries/base/dist-install/build:/home/abhir00p/ghc-8.8.2/libraries/integer-gmp/dist-install/build:/home/abhir00p/ghc-8.8.2/libraries/ghc-prim/dist-install/build:/home/abhir00p/ghc-8.8.2/rts/dist/build
libraries/ghc-boot-th_dist-install_DEP_LIB_REL_DIRS = libraries/base/dist-install/build libraries/integer-gmp/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/ghc-boot-th_dist-install_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/base/dist-install/build:libraries/integer-gmp/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/ghc-boot-th_dist-install_DEP_LD_OPTS = 
libraries/ghc-boot-th_dist-install_BUILD_GHCI_LIB = YES

$(eval $(libraries/ghc-boot-th_PACKAGE_MAGIC))
