ghc_stage1_VERSION = 8.8.2
ghc_stage1_COMPONENT_ID = ghc-bin-8.8.2
ghc_stage1_MODULES = Main
ghc_stage1_HIDDEN_MODULES = 
ghc_stage1_SYNOPSIS =The Glorious Glasgow Haskell Compiler.
ghc_stage1_HS_SRC_DIRS = .
ghc_stage1_DEPS = array-0.5.3.0 base-4.12.0.0 bytestring-0.10.8.2 directory-1.3.3.0 filepath-1.4.2.1 ghc-8.8.2 ghc-boot-8.8.2 process-1.6.5.0 unix-2.7.2.2
ghc_stage1_DEP_IPIDS = array-0.5.3.0 base-4.12.0.0 bytestring-0.10.8.2 directory-1.3.3.0 filepath-1.4.2.1 ghc-8.8.2 ghc-boot-8.8.2 process-1.6.5.0 unix-2.7.2.2
ghc_stage1_DEP_NAMES = array base bytestring directory filepath ghc ghc-boot process unix
ghc_stage1_DEP_COMPONENT_IDS = array-0.5.3.0 base-4.12.0.0 bytestring-0.10.8.2 directory-1.3.3.0 filepath-1.4.2.1 ghc-8.8.2 ghc-boot-8.8.2 process-1.6.5.0 unix-2.7.2.2
ghc_stage1_TRANSITIVE_DEP_NAMES = ghc terminfo process hpc ghci transformers template-haskell pretty ghc-heap ghc-boot ghc-boot-th directory unix time filepath binary containers bytestring deepseq array base integer-gmp ghc-prim rts
ghc_stage1_TRANSITIVE_DEP_COMPONENT_IDS = ghc-8.8.2 terminfo-0.4.1.4 process-1.6.5.0 hpc-0.6.0.3 ghci-8.8.2 transformers-0.5.6.2 template-haskell-2.15.0.0 pretty-1.1.3.6 ghc-heap-8.8.2 ghc-boot-8.8.2 ghc-boot-th-8.8.2 directory-1.3.3.0 unix-2.7.2.2 time-1.8.0.2 filepath-1.4.2.1 binary-0.8.7.0 containers-0.6.0.1 bytestring-0.10.8.2 deepseq-1.4.4.0 array-0.5.3.0 base-4.12.0.0 integer-gmp-1.0.2.0 ghc-prim-0.5.3 rts
ghc_stage1_INCLUDE_DIRS = 
ghc_stage1_INCLUDES = 
ghc_stage1_INSTALL_INCLUDES = 
ghc_stage1_EXTRA_LIBRARIES = 
ghc_stage1_EXTRA_LIBDIRS = 
ghc_stage1_S_SRCS = 
ghc_stage1_C_SRCS  = hschooks.c
ghc_stage1_CMM_SRCS = 
ghc_stage1_DATA_FILES = settings
ghc_stage1_HC_OPTS = -Wall -Wnoncanonical-monad-instances -Wnoncanonical-monoid-instances -threaded -XHaskell2010 -XNoImplicitPrelude
ghc_stage1_CC_OPTS = 
ghc_stage1_CPP_OPTS = 
ghc_stage1_LD_OPTS = 
ghc_stage1_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/home/abhir00p/ghc-8.8.2/compiler/.' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/.' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/.' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1/build/.' '/home/abhir00p/ghc-8.8.2/compiler/parser' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/parser' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/parser' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1/build/parser' '/home/abhir00p/ghc-8.8.2/compiler/utils' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/utils' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/utils' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1/build/utils' '/home/abhir00p/ghc-8.8.2/compiler/stage1' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1' '/home/abhir00p/ghc-8.8.2/compiler/stage1/build/stage1/build/stage1' '/usr/lib/ghc/process-1.6.5.0/include' '/usr/lib/ghc/process-1.6.5.0/dist-install/build/include' '/usr/lib/ghc/unix-2.7.2.2/include' '/usr/lib/ghc/unix-2.7.2.2/dist-install/build/include' '/usr/lib/ghc/time-1.8.0.2/include' '/usr/lib/ghc/time-1.8.0.2/dist-install/build/include' '/usr/lib/ghc/bytestring-0.10.8.2/include' '/usr/lib/ghc/bytestring-0.10.8.2/dist-install/build/include' '/usr/lib/ghc/base-4.12.0.0/include' '/usr/lib/ghc/base-4.12.0.0/dist-install/build/include' '/usr/lib/ghc/integer-gmp-1.0.2.0/include' '/usr/lib/ghc/integer-gmp-1.0.2.0/dist-install/build/include' '/usr/lib/ghc/include' '/usr/lib/ghc/dist-install/build/include'
ghc_stage1_DEP_CC_OPTS = 
ghc_stage1_DEP_LIB_DIRS_SEARCHPATH = /home/abhir00p/ghc-8.8.2/compiler/stage1/build:/home/abhir00p/ghc-8.8.2/libraries/terminfo/dist-boot/build:/usr/lib/ghc/process-1.6.5.0:/home/abhir00p/ghc-8.8.2/libraries/hpc/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/ghci/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/transformers/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/template-haskell/dist-boot/build:/usr/lib/ghc/pretty-1.1.3.6:/home/abhir00p/ghc-8.8.2/libraries/ghc-heap/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/ghc-boot/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/ghc-boot-th/dist-boot/build:/usr/lib/ghc/directory-1.3.3.0:/usr/lib/ghc/unix-2.7.2.2:/usr/lib/ghc/time-1.8.0.2:/usr/lib/ghc/filepath-1.4.2.1:/home/abhir00p/ghc-8.8.2/libraries/binary/dist-boot/build:/usr/lib/ghc/containers-0.6.0.1:/usr/lib/ghc/bytestring-0.10.8.2:/usr/lib/ghc/deepseq-1.4.4.0:/usr/lib/ghc/array-0.5.3.0:/usr/lib/ghc/base-4.12.0.0:/usr/lib/ghc/integer-gmp-1.0.2.0:/usr/lib/ghc/ghc-prim-0.5.3:/usr/lib/ghc/rts
ghc_stage1_DEP_LIB_REL_DIRS = compiler/stage2/build libraries/terminfo/dist-install/build libraries/process/dist-install/build libraries/hpc/dist-install/build libraries/ghci/dist-install/build libraries/transformers/dist-install/build libraries/template-haskell/dist-install/build libraries/pretty/dist-install/build libraries/ghc-heap/dist-install/build libraries/ghc-boot/dist-install/build libraries/ghc-boot-th/dist-install/build libraries/directory/dist-install/build libraries/unix/dist-install/build libraries/time/dist-install/build libraries/filepath/dist-install/build libraries/binary/dist-install/build libraries/containers/containers/dist-install/build libraries/bytestring/dist-install/build libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
ghc_stage1_DEP_LIB_REL_DIRS_SEARCHPATH = compiler/stage2/build:libraries/terminfo/dist-install/build:libraries/process/dist-install/build:libraries/hpc/dist-install/build:libraries/ghci/dist-install/build:libraries/transformers/dist-install/build:libraries/template-haskell/dist-install/build:libraries/pretty/dist-install/build:libraries/ghc-heap/dist-install/build:libraries/ghc-boot/dist-install/build:libraries/ghc-boot-th/dist-install/build:libraries/directory/dist-install/build:libraries/unix/dist-install/build:libraries/time/dist-install/build:libraries/filepath/dist-install/build:libraries/binary/dist-install/build:libraries/containers/containers/dist-install/build:libraries/bytestring/dist-install/build:libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
ghc_stage1_DEP_LD_OPTS = 
ghc_stage1_BUILD_GHCI_LIB = NO

$(eval $(ghc_PACKAGE_MAGIC))
