libraries/ghci_dist-boot_VERSION = 8.8.2
libraries/ghci_dist-boot_COMPONENT_ID = ghci-8.8.2
libraries/ghci_dist-boot_MODULES = GHCi.BreakArray GHCi.BinaryArray GHCi.Message GHCi.ResolvedBCO GHCi.RemoteTypes GHCi.FFI GHCi.InfoTable GHCi.StaticPtrTable GHCi.TH.Binary SizedSeq
libraries/ghci_dist-boot_HIDDEN_MODULES = 
libraries/ghci_dist-boot_SYNOPSIS =The library supporting GHC's interactive interpreter
libraries/ghci_dist-boot_HS_SRC_DIRS = .
libraries/ghci_dist-boot_DEPS = array-0.5.3.0 base-4.12.0.0 binary-0.8.7.0 bytestring-0.10.8.2 containers-0.6.0.1 deepseq-1.4.4.0 filepath-1.4.2.1 ghc-boot-8.8.2 ghc-boot-th-8.8.2 ghc-heap-8.8.2 template-haskell-2.15.0.0 transformers-0.5.6.2 unix-2.7.2.2
libraries/ghci_dist-boot_DEP_IPIDS = array-0.5.3.0 base-4.12.0.0 binary-0.8.7.0 bytestring-0.10.8.2 containers-0.6.0.1 deepseq-1.4.4.0 filepath-1.4.2.1 ghc-boot-8.8.2 ghc-boot-th-8.8.2 ghc-heap-8.8.2 template-haskell-2.15.0.0 transformers-0.5.6.2 unix-2.7.2.2
libraries/ghci_dist-boot_DEP_NAMES = array base binary bytestring containers deepseq filepath ghc-boot ghc-boot-th ghc-heap template-haskell transformers unix
libraries/ghci_dist-boot_DEP_COMPONENT_IDS = array-0.5.3.0 base-4.12.0.0 binary-0.8.7.0 bytestring-0.10.8.2 containers-0.6.0.1 deepseq-1.4.4.0 filepath-1.4.2.1 ghc-boot-8.8.2 ghc-boot-th-8.8.2 ghc-heap-8.8.2 template-haskell-2.15.0.0 transformers-0.5.6.2 unix-2.7.2.2
libraries/ghci_dist-boot_TRANSITIVE_DEP_NAMES = transformers template-haskell pretty ghc-heap ghc-boot ghc-boot-th directory unix time filepath binary containers bytestring deepseq array base integer-gmp ghc-prim rts
libraries/ghci_dist-boot_TRANSITIVE_DEP_COMPONENT_IDS = transformers-0.5.6.2 template-haskell-2.15.0.0 pretty-1.1.3.6 ghc-heap-8.8.2 ghc-boot-8.8.2 ghc-boot-th-8.8.2 directory-1.3.3.0 unix-2.7.2.2 time-1.8.0.2 filepath-1.4.2.1 binary-0.8.7.0 containers-0.6.0.1 bytestring-0.10.8.2 deepseq-1.4.4.0 array-0.5.3.0 base-4.12.0.0 integer-gmp-1.0.2.0 ghc-prim-0.5.3 rts
libraries/ghci_dist-boot_INCLUDE_DIRS = 
libraries/ghci_dist-boot_INCLUDES = 
libraries/ghci_dist-boot_INSTALL_INCLUDES = 
libraries/ghci_dist-boot_EXTRA_LIBRARIES = 
libraries/ghci_dist-boot_EXTRA_LIBDIRS = 
libraries/ghci_dist-boot_S_SRCS = 
libraries/ghci_dist-boot_C_SRCS  = 
libraries/ghci_dist-boot_CMM_SRCS = 
libraries/ghci_dist-boot_DATA_FILES = 
libraries/ghci_dist-boot_HC_OPTS = -XHaskell2010 -XNoImplicitPrelude
libraries/ghci_dist-boot_CC_OPTS = 
libraries/ghci_dist-boot_CPP_OPTS = 
libraries/ghci_dist-boot_LD_OPTS = 
libraries/ghci_dist-boot_DEP_INCLUDE_DIRS_SINGLE_QUOTED = '/usr/lib/ghc/unix-2.7.2.2/include' '/usr/lib/ghc/unix-2.7.2.2/dist-install/build/include' '/usr/lib/ghc/time-1.8.0.2/include' '/usr/lib/ghc/time-1.8.0.2/dist-install/build/include' '/usr/lib/ghc/bytestring-0.10.8.2/include' '/usr/lib/ghc/bytestring-0.10.8.2/dist-install/build/include' '/usr/lib/ghc/base-4.12.0.0/include' '/usr/lib/ghc/base-4.12.0.0/dist-install/build/include' '/usr/lib/ghc/integer-gmp-1.0.2.0/include' '/usr/lib/ghc/integer-gmp-1.0.2.0/dist-install/build/include' '/usr/lib/ghc/include' '/usr/lib/ghc/dist-install/build/include'
libraries/ghci_dist-boot_DEP_CC_OPTS = 
libraries/ghci_dist-boot_DEP_LIB_DIRS_SEARCHPATH = /home/abhir00p/ghc-8.8.2/libraries/transformers/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/template-haskell/dist-boot/build:/usr/lib/ghc/pretty-1.1.3.6:/home/abhir00p/ghc-8.8.2/libraries/ghc-heap/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/ghc-boot/dist-boot/build:/home/abhir00p/ghc-8.8.2/libraries/ghc-boot-th/dist-boot/build:/usr/lib/ghc/directory-1.3.3.0:/usr/lib/ghc/unix-2.7.2.2:/usr/lib/ghc/time-1.8.0.2:/usr/lib/ghc/filepath-1.4.2.1:/home/abhir00p/ghc-8.8.2/libraries/binary/dist-boot/build:/usr/lib/ghc/containers-0.6.0.1:/usr/lib/ghc/bytestring-0.10.8.2:/usr/lib/ghc/deepseq-1.4.4.0:/usr/lib/ghc/array-0.5.3.0:/usr/lib/ghc/base-4.12.0.0:/usr/lib/ghc/integer-gmp-1.0.2.0:/usr/lib/ghc/ghc-prim-0.5.3:/usr/lib/ghc/rts
libraries/ghci_dist-boot_DEP_LIB_REL_DIRS = libraries/transformers/dist-install/build libraries/template-haskell/dist-install/build libraries/pretty/dist-install/build libraries/ghc-heap/dist-install/build libraries/ghc-boot/dist-install/build libraries/ghc-boot-th/dist-install/build libraries/directory/dist-install/build libraries/unix/dist-install/build libraries/time/dist-install/build libraries/filepath/dist-install/build libraries/binary/dist-install/build libraries/containers/containers/dist-install/build libraries/bytestring/dist-install/build libraries/deepseq/dist-install/build libraries/array/dist-install/build libraries/base/dist-install/build libraries/integer-gmp/dist-install/build libraries/ghc-prim/dist-install/build rts/dist/build
libraries/ghci_dist-boot_DEP_LIB_REL_DIRS_SEARCHPATH = libraries/transformers/dist-install/build:libraries/template-haskell/dist-install/build:libraries/pretty/dist-install/build:libraries/ghc-heap/dist-install/build:libraries/ghc-boot/dist-install/build:libraries/ghc-boot-th/dist-install/build:libraries/directory/dist-install/build:libraries/unix/dist-install/build:libraries/time/dist-install/build:libraries/filepath/dist-install/build:libraries/binary/dist-install/build:libraries/containers/containers/dist-install/build:libraries/bytestring/dist-install/build:libraries/deepseq/dist-install/build:libraries/array/dist-install/build:libraries/base/dist-install/build:libraries/integer-gmp/dist-install/build:libraries/ghc-prim/dist-install/build:rts/dist/build
libraries/ghci_dist-boot_DEP_LD_OPTS = 
libraries/ghci_dist-boot_BUILD_GHCI_LIB = YES

$(eval $(libraries/ghci_PACKAGE_MAGIC))
